export const platformsMap = {
  p3do: "3DO",
  ags: "",
  amiga: "Amiga",
  amiga1200: "Amiga 1200",
  amiga600: "Amiga 600",
  amigacd32: "Amiga CD",
  amstradcpc: "Amstrad CPC",
  apple2: "Apple 2",
  apple2gs: "Apple 2GS",
  atari2600: "Atari 2600",
  atari5200: "Atari 5200",
  atari7800: "Atari 7800",
  atari800: "Atari 800",
  atarijaguar: "Atari Jaguar ",
  atarilynx: "Atari Lynx",
  atarist: "Atari ST",
  atarixe: "Atari XE",
  bbcmicro: "BBC Micro",
  c64: "Commodore 64",
  colecovision: "Colecovision",
  dos: "DOS",
  dreamcast: "Dreamcast",
  gameandwatch: "Game & Watch",
  gamecom: "Game.com",
  gamegear: "Game Gear",
  gb: "Game Boy",
  gba: "Game Boy Advance",
  gbc: "Game Boy Color",
  gc: "Gamecube",
  genesis: "Genesis",
  gx4000: "Amstrad GX4000",
  intellivision: "Intellivision",
  mastersystem: "Master System",
  megacd: "Sega CD",
  megadrive: "Megadrive",
  megaduck: "Megaduck",
  n3ds: "Nintendo 3DS",
  n64: "N64",
  nds: "Nintendo DS",
  neogeo: "NeoGeo",
  neogeocd: "NeoGeo CD",
  nes: "NES",
  ngage: "Ngage",
  ngp: "Neo Geo Pocket",
  ngpc: "Neo Geo Pocket Color",
  odyssey2: "Odyssey 2",
  pc88: "PC88",
  pc98: "PC98",
  pcengine: "PC Engine",
  pcenginecd: "PC Engine CD",
  pcfx: "PC-FX",
  pokemini: "Pokemon Mini",
  ps2: "Playstation 2",
  ps3: "Playstation 3",
  ps4: "Playstation 4",
  psp: "Playstation Portable",
  psvita: "Playstation Vita",
  psx: "Playstation 1",
  saturn: "Sega Saturn",
  sega32x: "Sega 32X",
  segacd: "Sega CD",
  sg1000: "Sega SG1000",
  sgb: "Super Game Boy",
  snes: "Super Nintendo",
  solarus: "Solarus",
  spectravideo: "Spectravideo",
  supergrafx: "PC Engine SuperGrafx",
  supervision: "Supervision",
  supracan: "Supracan",
  switch: "Switch",
  tg16: "TurboGrafx-16",
  tgcd: "TurboGrafx CD",
  vectrex: "Vectrex",
  virtualboy: "Virtual Boy",
  wii: "Wii",
  wiiu: "WiiU",
  windows: "Windows",
  wonderswan: "Wonderswan",
  wonderswancolor: "Wonderswan Color",
  xbox: "Xbox",
  xbox360: "Xbox 360",
  zx81: "ZX81",
  zxnext: "ZX Spectrum Next",
  zxspectrum: "ZX Spectrum",
};
